# Generated by Django 4.2.2 on 2023-06-26 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0002_alter_investmentmodel_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestmentModel',
            new_name='Investment',
        ),
    ]
